version: '3.8'

services:
  # Service 1: MySQL Database
  mysqldb:
    image: mysql:latest
    container_name: mysqldb_container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=newdba
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  # Service 2: Spring Boot Application
  app:
    build: .
    container_name: spring_app_container
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/newdba
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

volumes:
  db_data: